// <auto-generated />
using System;
using GeciciTSweb.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeciciTSweb.Infrastructure.Migrations
{
    [DbContext(typeof(GeciciTSwebDbContext))]
    partial class GeciciTSwebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.Companies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.Console", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Consoles");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.MaintenanceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BildirimNumarasi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Fluid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Pressure")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TempMaintenanceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Temperature")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TempMaintenanceTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("MaintenanceRequests");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.RequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaintenanceRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("MaintenanceRequestId");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.RiskAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("DATETIME2(0)");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CancelReasonCode")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CancelReasonText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2(0)")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentImpact")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentProbability")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentRPN")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentCode")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentReportNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DepartmentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaintenanceRequestId")
                        .HasColumnType("int");

                    b.Property<string>("OperationalRiskNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PlannedPermanentRepairDate")
                        .HasColumnType("DATETIME2(0)");

                    b.Property<DateTime?>("PlannedTemporaryRepairDate")
                        .HasColumnType("DATETIME2(0)");

                    b.Property<int?>("ResidualImpact")
                        .HasColumnType("int");

                    b.Property<int?>("ResidualProbability")
                        .HasColumnType("int");

                    b.Property<int?>("ResidualRPN")
                        .HasColumnType("int");

                    b.Property<string>("ReturnReasonCode")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReturnReasonText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RiskCategoryCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2(0)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CurrentRPN")
                        .HasDatabaseName("IX_RA_CurrentRPN");

                    b.HasIndex("DepartmentStatus")
                        .HasDatabaseName("IX_RA_Status");

                    b.HasIndex("MaintenanceRequestId");

                    b.HasIndex("ResidualRPN")
                        .HasDatabaseName("IX_RA_ResidualRPN");

                    b.HasIndex("MaintenanceRequestId", "DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("IX_RA_MaintenanceRequest_Department_Unique")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("RiskAssessments", t =>
                        {
                            t.HasCheckConstraint("CK_RiskAssessment_DepartmentCode", "[DepartmentCode] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_RiskAssessment_DepartmentStatus", "[DepartmentStatus] IN ('Degerlendirme', 'OnayBekliyor', 'Onaylandi', 'GeriGonderildi', 'Iptal')");
                        });
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.TemporaryMaintenanceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TemporaryMaintenanceTypes");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsoleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConsoleId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.Console", b =>
                {
                    b.HasOne("GeciciTSweb.Infrastructure.Entities.Companies", "Company")
                        .WithMany("Consoles")
                        .HasForeignKey("CompanyId")
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("GeciciTSweb.Infrastructure.Entities.User", "CreatedByUser")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired();

                    b.HasOne("GeciciTSweb.Infrastructure.Entities.TemporaryMaintenanceType", "TempMaintenanceType")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("TempMaintenanceTypeId")
                        .IsRequired();

                    b.HasOne("GeciciTSweb.Infrastructure.Entities.Unit", "Unit")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("UnitId")
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("TempMaintenanceType");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.RiskAssessment", b =>
                {
                    b.HasOne("GeciciTSweb.Infrastructure.Entities.User", "ApprovedByUser")
                        .WithMany("ApprovedRiskAssessments")
                        .HasForeignKey("ApprovedByUserId");

                    b.HasOne("GeciciTSweb.Infrastructure.Entities.User", "CreatedByUser")
                        .WithMany("CreatedRiskAssessments")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired();

                    b.HasOne("GeciciTSweb.Infrastructure.Entities.MaintenanceRequest", "MaintenanceRequest")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("MaintenanceRequestId")
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("MaintenanceRequest");
                });



            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.Unit", b =>
                {
                    b.HasOne("GeciciTSweb.Infrastructure.Entities.Console", "Console")
                        .WithMany("Units")
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Console");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.Companies", b =>
                {
                    b.Navigation("Consoles");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.Console", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.MaintenanceRequest", b =>
                {

                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.TemporaryMaintenanceType", b =>
                {
                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.Unit", b =>
                {
                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("GeciciTSweb.Infrastructure.Entities.User", b =>
                {
                    b.Navigation("ApprovedRiskAssessments");

                    b.Navigation("CreatedRiskAssessments");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("RequestLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
